### ISSUE TITLE
Converting to onnx

### ISSUE THREAD

**Issue by hossein-moghaddam** [pengtougu/onnx-scrfd-flask#2]
Hi 
This question is completely irrelevant but can you explain how did you convert the models to ONNX? which mmdet and mmcv version did you use? thank you so much.

**Comment by ppogg** [comment]
Sure, I am willing to answer for you：
![image](https://user-images.githubusercontent.com/82716366/132522483-cf9b6135-e2ae-424b-81eb-721f579dcbb1.png)
The information you want is as above~
If you want more details, you can read this blog：
[https://zhuanlan.zhihu.com/p/377561559](https://zhuanlan.zhihu.com/p/377561559)

**Comment by hossein-moghaddam** [comment]
Thank you :)
